name: Oneiron
version: 0.3.0
author: Kasyyy
api-version: 1.14
main: de.kasyyy.oneiron.main.Oneiron
database: true
load: POSTWORLD
commands:
  cspawner:
    description: Creates a spawner for oneiron mobs
  cspawn:
    description: Spawns a custom mob
  spawnerdebug:
    description: Makes all Oneiron Spawners visible
  oneironitems:
    description: A list of all items
  setrace:
    description: Sets a players race
  lvlreset:
    description: Resets a players level and race